// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uufownxgxmumhotchbpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1Zm93bnhneG11bWhvdGNoYnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDAxNzUsImV4cCI6MjA2NTcxNjE3NX0.5ZMrmHSusg6ZxZvvswP8zYKRwh7J445CGSgGKnuXk_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);